### ISSUE TITLE
Shooter Subsystem

### ISSUE THREAD

**Issue by connerebbinghaus** [RedHotChiliBots/FRC4453_2018_PROJ#1]
The shooter consists of:
- A motor to compress the spring
- A Double Solenoid to hold the shooter in place
- A limit switch to detect when the spring is fully compressed
- And a magnetic clutch that needs to be released before firing.

General operation looks like:
- The clutch engages, and the motor spins in one direction to compress the spring.
- When the limit switch is hit, the motor stops, the solenoid engages, and (a few moments later) the clutch disengages.
- The robot then waits for the command to shoot.
- When told to shoot, the robot disengages the solenoid, releasing the shooter.

Required methods:
- public void prepare() : prepare the shooter to fire.
- public void fire() : fires the shooter.

**Comment by OddCryptid** [comment]
It is complete.

**Comment by larsenmae** [comment]
Yes it is.
