### ISSUE TITLE
Write the Grabber Subsystem code.

### ISSUE THREAD

**Issue by connerebbinghaus** [RedHotChiliBots/FRC4453_2018_PROJ#2]
The grabber needs code written for it. The actuators, sensors and general operation must be known first.

**Comment by connerebbinghaus** [comment]
@RedHotChiliBots/mechanical What will the Grabber subsystem consist of? In terms of actuators and sensors.

**Comment by mcseifert** [comment]
The grabber will have two pistons to open and close the jaws they will be double action.
There are two intake bag motors that need to run both ways.
There is a single high torque motor that will rotate the grabber to pick up and drop blocks, the motor has an encoder built into it.
There needs to be a limit switch to zero the grabber so the robot knows where the grabber is.

Matthew Seifert

**Comment by connerebbinghaus** [comment]
Code has been written. Closing...
