### ISSUE TITLE
Write the Climber Subsystem Code.

### ISSUE THREAD

**Issue by connerebbinghaus** [RedHotChiliBots/FRC4453_2018_PROJ#3]
We need to write as much of the climber code ahead of time, as it look like it will be the most complex subsystem in terms of software.
Actuators:
- Two motors

Sensors:
- Gyroscope

The robot will need to keep itself level while climbing, even if the robot's weight is uneven.

**Comment by connerebbinghaus** [comment]
@RedHotChiliBots/mechanical Are there any other actuators or sensors needed for the climber?

**Comment by mcseifert** [comment]
Do you have encoders on the motors?

**Comment by connerebbinghaus** [comment]
Yes, I do. If no other actuators are needed, this can be closed.
