### ISSUE TITLE
Write the Lifter Subsystem Code.

### ISSUE THREAD

**Issue by connerebbinghaus** [RedHotChiliBots/FRC4453_2018_PROJ#4]
The lifter needs to be able to carry two other robots. It will consist of two wings that will drop down.
From a software prespective, all that needs to be done is to drop the two wings. The wings should not be allowed to drop until endgame.

**Comment by connerebbinghaus** [comment]
@RedHotChiliBots/mechanical What actuators are we using to drop the wings?

**Comment by mcseifert** [comment]
We are using 2in pistons with a 3/4in bore. The pistons will be pressurized to keep the lift wings from falling and they will release their pressure to lower the wings.

Matthew Seifert

**Comment by larsenmae** [comment]
Done.
